### ISSUE TITLE
启动时报错：No provider available

### ISSUE THREAD

**Issue by lgxbslgx** [jnudeveloper/dubbo-demo-client#1]
提示`No provider available`, 报错信息如下：

```Java
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'demoController': Unsatisfied dependency expressed through field 'demoService'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'demoService': FactoryBean threw exception on object creation; nested exception is java.lang.IllegalStateException: Failed to check the status of the service com.demo.service.DemoService. No provider available for the service com.demo.service.DemoService from the url multicast://224.5.6.7:1234/org.apache.dubbo.registry.RegistryService?application=dubbo-demo-client&default.lazy=false&default.sticky=false&dubbo=2.0.2&interface=com.demo.service.DemoService&lazy=false&methods=sayHello&pid=7564&qos.accept.foreign.ip=false&qos.enable=true&qos.port=33333&register.ip=127.0.0.1&release=2.7.1&side=consumer&sticky=false&timestamp=1557230007796 to the consumer 127.0.0.1 use dubbo version 2.7.1
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:586)
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:87)
        ...
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:688)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:687)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'demoService': FactoryBean threw exception on object creation; nested exception is java.lang.IllegalStateException: Failed to check the status of the service com.demo.service.DemoService. No provider available for the service com.demo.service.DemoService from the url multicast://224.5.6.7:1234/org.apache.dubbo.registry.RegistryService?application=dubbo-demo-client&default.lazy=false&default.sticky=false&dubbo=2.0.2&interface=com.demo.service.DemoService&lazy=false&methods=sayHello&pid=7564&qos.accept.foreign.ip=false&qos.enable=true&qos.port=33333&register.ip=127.0.0.1&release=2.7.1&side=consumer&sticky=false&timestamp=1557230007796 to the consumer 127.0.0.1 use dubbo version 2.7.1
	at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.doGetObjectFromFactoryBean(FactoryBeanRegistrySupport.java:185)
	at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.getObjectFromFactoryBean(FactoryBeanRegistrySupport.java:103)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getObjectForBeanInstance(AbstractBeanFactory.java:1646)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:254)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:208)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.addCandidateEntry(DefaultListableBeanFactory.java:1317)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.findAutowireCandidates(DefaultListableBeanFactory.java:1283)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1102)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1067)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:583)
	... 62 more
Caused by: java.lang.IllegalStateException: Failed to check the status of the service com.demo.service.DemoService. No provider available for the service com.demo.service.DemoService from the url multicast://224.5.6.7:1234/org.apache.dubbo.registry.RegistryService?application=dubbo-demo-client&default.lazy=false&default.sticky=false&dubbo=2.0.2&interface=com.demo.service.DemoService&lazy=false&methods=sayHello&pid=7564&qos.accept.foreign.ip=false&qos.enable=true&qos.port=33333&register.ip=127.0.0.1&release=2.7.1&side=consumer&sticky=false&timestamp=1557230007796 to the consumer 127.0.0.1 use dubbo version 2.7.1
	at org.apache.dubbo.config.ReferenceConfig.createProxy(ReferenceConfig.java:390)
	at org.apache.dubbo.config.ReferenceConfig.init(ReferenceConfig.java:305)
	at org.apache.dubbo.config.ReferenceConfig.get(ReferenceConfig.java:231)
	at org.apache.dubbo.config.spring.ReferenceBean.getObject(ReferenceBean.java:71)
	at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.doGetObjectFromFactoryBean(FactoryBeanRegistrySupport.java:178)
	... 72 more

```

**Comment by lgxbslgx** [comment]
已经解决。tomcat启动时间过长超过了zookeeper的tickTime，导致查找服务失败，把tickTime设置长一点即可。

**Comment by lgxbslgx** [comment]
关闭issue
